name: Upload Modules

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_LOGIN }}
        
      - name: rg-create
        run: |
          az group create -l brazilsouth -n rg-poc-demogenerated-dev

      - name: Create Azure Container registry
        run: |
          az deployment group create --resource-group rg-poc-demogenerated-dev --template-file ./modulos/acr.bicep --parameters appName=demogenerated environment=dev clusterNUm=001

      
      - name: Upload RG Module
        run: |
          az bicep publish --file ./modulos/rg.bicep --target br:acrdemogenerateddev001.azurecr.io/bicep/modules/rg:v1

      - name: Upload ACR Module
        run: |
          az bicep publish --file ./modulos/acr.bicep --target br:acrdemogenerateddev001.azurecr.io/bicep/modules/acr:v1

      - name: Upload AKV Module
        run: |
          az bicep publish --file ./modulos/akv.bicep --target br:acrdemogenerateddev001.azurecr.io/bicep/modules/akv:v1

      - name: Upload AKS Module
        run: |
          az bicep publish --file ./modulos/aks.bicep --target br:acrdemogenerateddev001.azurecr.io/bicep/modules/aks:v1

      - name: Upload appgw Module
        run: |
          az bicep publish --file ./modulos/appgw.bicep --target br:acrdemogenerateddev001.azurecr.io/bicep/modules/appgw:v1
        
      - name: Upload publicip Module
        run: |
          az bicep publish --file ./modulos/publicip.bicep --target br:acrdemogenerateddev001.azurecr.io/bicep/modules/publicip:v1

      - name: Upload subnet Module
        run: |
          az bicep publish --file ./modulos/subnet.bicep --target br:acrdemogenerateddev001.azurecr.io/bicep/modules/subnet:v1

      - name: Upload vnet Module
        run: |
          az bicep publish --file ./modulos/vnet.bicep --target br:acrdemogenerateddev001.azurecr.io/bicep/modules/vnet:v1

      - name: Upload webapp Module
        run: |
          az bicep publish --file ./modulos/webapp.bicep --target br:acrdemogenerateddev001.azurecr.io/bicep/modules/webapp:v1





