# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_LOGIN }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: az bicep publish --file ./modulos/rg.bicep --target br:ghcr.io/${{ github.actor }}/bicep/modules/rg:v1

